config/routes.rb
Stack::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :categories do

    resources :links
    
  end

  root "categories#index"

  

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base

	# let the category know about the links
	has_many :links
	
	# let's add some validations to make sure the data is what we want it to be
	validates :name, presence: true, uniqueness: {message: "already gone", case_sensitive: false }
	validates :rank, presence: true, numericality: { greater_than: 0 }


end

app/models/link.rb
require "obscenity/active_model"

class Link < ActiveRecord::Base

	# let's link up this model with the category
	belongs_to :category

	# add some validations
	validates :name, presence: true, obscenity: { sanitize: true, replacement: :vowels }
	validates :url, presence: true, uniqueness: true

	# i've made this nice_url thing up
	def nice_url
		# lets remove http:// and lets remove www.
		url.gsub("http://", "").gsub("www.", "")
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	# i want to run get_category before the show, edit, update, destroy
	# and i don't want to keep having to repeat the same code over and over
	# we can use before_action to do things before any method (a.k.a. action)
	before_action :get_category, only: [:show, :edit, :update, :destroy]

	# Step 2 is to add in an index page
	# we want to define the index of our controller

	def index
		# this is where all of our code for the index page lives
		
		# quotes denote a string 
		# a string is some data
		@username = "cleverGoat"

		# age is only a number so it does not need quotes around it
		@age = 31

		# to do a list, we use an array
		# @categories = ["Design", "Rails", "Javascript", "Site tools"]

		# now lets talk to the model
		@categories = Category.all.order("rank asc, name asc")
	end


	# individual page for the category
	def show		
		# @category is in get_category
	end


	# the new form for a category
	def new
		@category = Category.new
	end


	# actually add the category using the data the form has in it
	def create
		@category = Category.new(category_params)

		if @category.save
			
			# tell the user they've added this category
			flash[:success] = @category.name + " Added"

			# go back to the homepage
			redirect_to root_path

		else
			
			# if the category does NOT save
			# i want to show the form again but with some errors

			# we've already got the view that we want to show to the user
			# this is the new.html.erb
			render "new"


		end

	end


	# get a form to edit this category
	def edit
		# @category is in get_category
	end


	# actually update the row in the database
	def update

		# update based on the secure form data from below

		if @category.update(category_params)
		
			# tell the user they've updated this category
			flash[:success] = @category.name + " Updated"
		
			# redirect to the homepage
			redirect_to root_path

		else
		
			# show the edit form again if it doesn't update
			# edit.html.erb in our views
			render "edit"

		end

	end
	

	# actually delete the category in the database
	def destroy

		# destroy that row
		@category.destroy

		# tell the user they've deleted this category
		flash[:success] = @category.name + " Deleted"
		
		# go back to the home page
		redirect_to root_path
	
	end


	# to not repeat ourselves, let's create a brand new method
	# to simplify things
	# i can call a method whatever i like
	def get_category
		@category = Category.find(params[:id])
	end


	# whitelist all of the form data
	# make sure we are secure from hackers
	def category_params
		params.require(:category).permit(:name, :rank)
	end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	 
  # before EVERYTHING in here, find the category 
  before_action :get_category

  # before EDIT, UPDATE, and DESTROY, find the link
  before_action :get_link, only: [:edit, :update, :destroy]


  def new

  	if params[:duplicate_id].present?
  		# do a duplicate of this
  		@duplicate_link = @category.links.find(params[:duplicate_id])
  		@link = @category.links.new(@duplicate_link.attributes)
  	else
  		# do a brand new one
  		@link = @category.links.new
  	end

  end


  def create
  	@link = @category.links.new(link_params)
  	if @link.save
  		flash[:success] = "Link added"
  		redirect_to category_path(@category)
  	else
  		render :new
  	end
  end


  def edit
  	# i want to find the link within the category
  end


  def update
  	if @link.update(link_params)
  		flash[:success] = "Link updated"
  		redirect_to category_path(@category)
  	else
 		render :edit
  	end
  end


  def destroy
  	@link.destroy
  	flash[:success] = "Link was deleted"
  	redirect_to category_path(@category)
  end


  # only allow the following from the form in order to stop people from hacking our site
  def link_params
  	params.require(:link).permit(:name, :description, :url, :is_recommended)
  end


  def get_category
  	# because we're not in the categories controller
  	# we need to find the ID of the category
  	# using the /categories/:category_id/links/new
  	@category = Category.find(params[:category_id])
  end


  def get_link
  	@link = @category.links.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>

	<%= f.input :name, label: "Category name" %>
	<%= f.input :rank %>

	<%= f.button :submit %>

<% end %>

app/views/categories/edit.html.erb
<h2>Edit category</h2>

<%= render "form" %>

app/views/categories/index.html.erb
<h2>It's my Uber Homepage</h2>

<p>
	The time now is... <%= Time.now %>
</p>

<p>
	Username is <strong><%= @username %></strong> and they are <%= @age %> years old. In 20 years time they will be <%= @age + 20 %> years old.
</p>

<ul class="category-list">
	<!-- loop over the @categories -->
	<!-- note: no = tag as we don't want to print out the list -->
	
	<!-- for each thing in @categories -->
	<!-- call it "category" -->
	<% @categories.each do |category| %>
	
	<!-- print it out into a list -->
	<li>
		<div class="details">
			<%= link_to category.name, category_path(category) %>
		</div>
		<div class="actions">
			<%= link_to "Edit", edit_category_path(category), class: "edit" %>

			<%= link_to "Delete", category_path(category), method: :delete, class: "delete", confirm: "Are you sure you want to delete this category?" %>
		</div>

	</li>

	<% end %>
</ul>

<!-- link_to is more flexible for changing URLs later on -->

<%= link_to "New Category", new_category_path, class: "button" %>

app/views/categories/new.html.erb
<h2>Add a category</h2>

<%= render "form" %>

app/views/categories/show.html.erb
<section>

	<% @category.links.each do |link| %>

		<div class="link">

			<div class="details">
				<h3><%= link_to link.name, link.url %></h3>
				<p><%= link.description %></p>
				<p><%= link_to link.nice_url, link.url %>

					<% if link.is_recommended? %>
						<span> - Highly recommended</span>
					<% end %>
				
				</p>
			</div>

			<div class="actions">
				<%= link_to "Edit", edit_category_link_path(@category, link), class: "edit" %>

				<%= link_to "Duplicate", new_category_link_path(@category, duplicate_id: link.id), class: "edit" %>

				<%= link_to "Delete", category_link_path(@category, link), method: :delete, class: "delete", confirm: "Are you sure you want to delete?" %>

			</div>

		</div>

	<% end %>


</section>



<%= link_to "Add new link", new_category_link_path(@category), class: "button" %>
<%= link_to "Back to the categories", root_path, class: "button" %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Stack</title>
		<%= stylesheet_link_tag		"application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<header>
			<%= link_to image_tag("/assets/stack-logo.png"), "#" %> Resources
		</header>

		<% flash.each do |key, value| %>
			<div class="flash <%= key %>"><%= value %></div>
		<% end %>

		<%= yield %>

		<footer>
			Stack is a list of resources that makes learning to code easier.
		</footer>

	</body>
</html>

app/views/links/_form.html.erb
<%= simple_form_for [@category, @link] do |f| %>

	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :url %>
	<%= f.input :is_recommended %>

	<%= f.button :submit %>

<% end %>

app/views/links/edit.html.erb
<h2>Edit <%= @link.name %></h2>

<%= render "form" %>

app/views/links/new.html.erb
<h2>Add a link to the <%= @category.name %> category</h2>

<%= render "form" %>